DROP TABLE test_table;

CREATE TABLE test_table (
    myid NUMBER GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR2(100),
    PRIMARY KEY (myid)
)
/

BEGIN
  FOR i IN 1..2000 LOOP
    INSERT INTO test_table (name)
    VALUES ('Name_' || i);
  END LOOP;
  COMMIT;
END;
/


ALTER TABLE test_table modify partition by range (myid) (
    PARTITION p1 VALUES LESS THAN (1000),
    PARTITION p2 VALUES LESS THAN (2000),
    PARTITION p3 VALUES LESS THAN (3000)
) online including rows where myid > 100;

/*
ALTER TABLE test_table MODIFY PARTITION BY RANGE (myid)
  (
    PARTITION p1 VALUES LESS THAN (1000)
  ) online including rows where myid > 100;
*/

  ALTER TABLE test_table DROP PARTITION p1;


  SELECT COUNT(*) FROM test_table;
